### ISSUE TITLE
Just Recommendation!! Need Tutorial for HOWTO current position (angles or coords) 

### ISSUE THREAD

**Issue by MorrisLu-Taipei** [elephantrobotics/mycobot-tutorial#1]
Hi

Need Tutorial for HOWTO current position (angles or coords) 

Any tips for  current position (angles or coords) into blockly (ony working for roboflow?)

For example, in free mode, we can adjust all joint to specific position A, then position B 
But in UIflow 3paty-mycobot, cannot detect current position [0,0,0,0,0,0] . must input value position (angles or coords) by ourselves 

![image](https://user-images.githubusercontent.com/22585297/110424649-14809c00-80de-11eb-83af-a95a188c2f78.png)

**Comment by zlj-zz** [comment]
I'm not sure if I understand what you mean. Can the following meet your needs?
<img width="1472" alt="demo-1" src="https://user-images.githubusercontent.com/27907644/110723088-76601380-824e-11eb-9f2f-8a94ee5eba3e.png">
